### ISSUE TITLE
Option to disable all concealing

### ISSUE THREAD

**Issue by djmitche** [ixru/nvim-markdown#12]
It appears that regardless of `g:vim_markdown_conceal`, the single-backtick and triple-backtick syntax is still concealed. The triple-backticks is particularly problematic for me, as it appears to be a redundant empty line.

Can we have an option to disable all concealing?

**Comment by ixru** [comment]
The vim syntax file is janky. I use the treesitter syntax, and I would suggest using that. I think I might remove the syntax file completely. If you want a fix, I know preservim merged some changes. It's too arcane for me to bother with.

**Comment by djmitche** [comment]
I don't see any docs for the treesitter syntax -- what is that?

**Comment by ixru** [comment]
https://github.com/nvim-treesitter/nvim-treesitter

**Comment by djmitche** [comment]
Ah, I see -- so using a different treesitter plugin altogether. I thought you meant there was some un-documented way to configure this package via the treesitter config. Thanks!
