### ISSUE TITLE
`BufWinLeave` bug on LSP floating view

### ISSUE THREAD

**Issue by joaomendoncaa** [ixru/nvim-markdown#17]
## Problem

In nvim >0.10 (at least that's when I started noticing it), [this autocommand](https://github.com/ixru/nvim-markdown/blob/75639723c1a3a44366f80cff11383baf0799bcb5/ftplugin/markdown.vim#L735) is throwing a non-silent `E32` when you try to jump inside the LSP info floating view. 

**The error happens because the plugin recognizes these floating windows as valid markdown buffers and, when leaving the buffer, it tries to save it without success because there's no name on that buffer.**

Here's a quick demo: 

https://github.com/ixru/nvim-markdown/assets/57664150/b98ca875-f89d-49dc-94d7-b2cb0f0439b0

## Solution

I don't have much time for a PR right now but because the bug was pissing me off I [forked the repo](https://github.com/joaomendoncaa/nvim-markdown) and made a [quick and nasty band-aid](https://github.com/ixru/nvim-markdown/commit/f301e3cd1c493340848405b883a96f2b1c030b90). It might not be of great value for a PR since it will probably conflict with a few edge cases and it's crappy vim script with 0 documentation aswell. But what it does is simple in principle; checks if the window is floating and only applies the autocommand if it is not a floating window. 

Hopefully this inspires someone to fix the problem in a serious manner.

Cheers and thank you for your time! 🍻

**Comment by ixru** [comment]
https://vi.stackexchange.com/questions/13864/bufwinleave-mkview-with-unnamed-file-error-32 Could you test if this fixes it?

**Comment by joaomendoncaa** [comment]
> https://vi.stackexchange.com/questions/13864/bufwinleave-mkview-with-unnamed-file-error-32 Could you test if this fixes it?

I may be missing something here, but that's the exact problem; I don't want to save the "markdown buffer" on the floating view.

What exactly on that answer do you foresee solving the problem? 🤔

**Comment by ixru** [comment]
I was a little hasty, it's not as simple as the answer.
You can test changing [this line](https://github.com/ixru/nvim-markdown/blob/75639723c1a3a44366f80cff11383baf0799bcb5/ftplugin/markdown.vim#L735) to `autocmd BufWinLeave *? if &ft=='markdown' | mkview! | endif`, a little messy but I hope it works. I don't know if it errors on the line below too, but if it does the same change should work for that too.

**Comment by ixru** [comment]
On second thought maybe you can just put a `silent!` on it `autocmd BufWinLeave <buffer> silent! mkview!`
