### ISSUE TITLE
Setting vim_markdown_conceal=0 doesn't work

### ISSUE THREAD

**Issue by jceb** [ixru/nvim-markdown#18]
I tried to disable concealing but it didn't work. My suspicion is that this line butchers the conceal configuration: https://github.com/ixru/nvim-markdown/blob/75639723c1a3a44366f80cff11383baf0799bcb5/ftplugin/markdown.vim#L755

**Comment by ixru** [comment]
I don't know, I think how it's supposed to work is that the conceallevel is always 2, but it adjusts exactly what can be concealed with vim_markdown_conceal. Seems kinda stupid to me now, but I'm not going to look into it, I will just remove all the syntax stuff eventually. I believe treesitter overrules all of it, you might want to check if that is messing with it. If it is, the plugin will lock you to conceallevel=2, out of luck.

**Comment by ixru** [comment]
Probably fixed by #23
