### ISSUE TITLE
[Question] Change the map C-c for other?

### ISSUE THREAD

**Issue by chriztheanvill** [ixru/nvim-markdown#2]
Hi.
I am get to use C-c to use like Esc key. How could I change this shortcut key ?
I love your Plugin :D

**Comment by ixru** [comment]
I will remove C-c from insert mode, is it bad to have it mapped in normal mode too?
You can fork and edit [these lines](https://github.com/ixru/nvim-markdown/blob/master/ftplugin/markdown.vim#L771) if there's something you really want to change.

**Comment by patrick96** [comment]
Maybe you could add an option to disable all keymaps, then users can decide themselves what mappings they want to use.

**Comment by ixru** [comment]
Yes I did that. You can see how to remap here https://github.com/ixru/nvim-markdown/#mappings
Please tell if you have more ideas.

**Comment by patrick96** [comment]
Cool :smiley:

**Comment by chriztheanvill** [comment]
Thank you so much :D
