### ISSUE TITLE
Readd `:TableFormat`

### ISSUE THREAD

**Issue by kmoschcau** [ixru/nvim-markdown#8]
Would it be possible to readd the `:TableFormat` command to auto format tables? The old vim-markdown had it, but here it is missing.

**Comment by ixru** [comment]
I don't remember why I removed it. I think maybe it was broken, but I will add it.

**Comment by ixru** [comment]
Added, I can't be bothered testing it. Tell me if it doesn't work

**Comment by kmoschcau** [comment]
Hey thanks. I only got around to validate it a small bit today and it seems to be working fine.
